### ISSUE TITLE
Allow degree subjects to be mapped to an array of HESA codes

### ISSUE THREAD

**Issue by frankieroberto** [DFE-Digital/dfe-reference-data#14]
Some subjects, such as "English language and literature" should be mapped to 2 HESA codes, which can then be both submitted in the HESA ITT return.

We could consider either making all these HESA ITT codes appear in an array (mostly of 1 item) or allow either a string or an array to be present. Possibly the former would be more intuitive for downstream users of the data?

**Comment by alaric-dfe** [comment]
I vote for always an array rather than array-or-string, it's neater for users as you say.

**Comment by frankieroberto** [comment]
We could possibly close this now, as I think we resolved this with the "combined subjects" feature?
